controller_manager_ns: /trobo/controller_manager
controller_list:
  - name: /trobo/joint1_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
#    gains:
#      joint1: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
